### ISSUE TITLE
Responsive Design for Laptop needed

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/ReportingSourcing#2]
need a responsive Design for a 14" Laptop (please edit file at public/css/responsive/laptop.css)

**Comment by jiwendi** [comment]
Hi. Where is the css folder? I would like to work on this

**Comment by vJechsmayr** [comment]
Hi! CSS folder is in SourcingReporting_NodeJS/public/CSS/responsive/laptop.css
Current CSS Styles are in SourcingReporting_NodeJS/public/CSS/sourcing.css
